language: php

php:
  - 5.3
  - 5.4

before_install:
  - cd ../
  - git clone git://github.com/UnionOfRAD/framework.git
  - mv li3_analytics/ framework/app/libraries/li3_analytics
  - cd framework
  - git submodule update --init --recursive
  - cd app/libraries/

script: ../../../libraries/lithium/console/li3 test ./tests